services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 8080:80
    environment:
      - BACKEND_URL=http://backend:3001

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
