FROM node:20-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable
COPY . /repo
WORKDIR /repo
RUN pnpm install --prod --frozen-lockfile

EXPOSE 3001

ENTRYPOINT [ "pnpm", "run", "start:backend" ]
